version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: 682263059097.dkr.ecr.us-east-1.amazonaws.com/account_service
    container_name: account_service
    ports:
      - "8002:8002"
    environment:
      KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
    networks:
      - custservice_imnetwork
networks:
  custservice_imnetwork:
    external: true
